-- Добавить поля subtasks и plan в таблицу tasks
ALTER TABLE public.tasks 
ADD COLUMN IF NOT EXISTS subtasks text,
ADD COLUMN IF NOT EXISTS plan text;

-- Привязка задач к проектам и расширенные поля
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS task_type text,
  ADD COLUMN IF NOT EXISTS complexity text,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'todo',
  ADD COLUMN IF NOT EXISTS story_points integer,
  ADD COLUMN IF NOT EXISTS assignee_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS tags text[],
  ADD COLUMN IF NOT EXISTS depends_on bigint[],
  ADD COLUMN IF NOT EXISTS checklist jsonb,
  ADD COLUMN IF NOT EXISTS attachments jsonb;

-- Комментарии для полей
COMMENT ON COLUMN public.tasks.subtasks IS 'JSON-строка с подзадачами, созданными ИИ';
COMMENT ON COLUMN public.tasks.plan IS 'JSON-строка с планом дня, созданным ИИ';

------------------------------------------------------------------
-- ПОЛЬЗОВАТЕЛИ / РОЛИ / РЕГИСТРАЦИЯ
------------------------------------------------------------------

-- Профили пользователей (связан с auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  full_name text,
  role text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'moderator', 'admin')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Дополнительные поля профиля (для блокировок и расширенного функционала)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_blocked boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_email_key ON public.profiles (email);

COMMENT ON TABLE public.profiles IS 'Профили пользователей, привязанные к auth.users';
COMMENT ON COLUMN public.profiles.role IS 'Роль пользователя: user / moderator / admin';
COMMENT ON COLUMN public.profiles.is_blocked IS 'Флаг блокировки пользователя (true = вход запрещён)';

-- Представление для модераторов
CREATE OR REPLACE VIEW public.moderators AS
  SELECT * FROM public.profiles WHERE role = 'moderator';

-- Представление для администраторов
CREATE OR REPLACE VIEW public.admins AS
  SELECT * FROM public.profiles WHERE role = 'admin';

COMMENT ON VIEW public.moderators IS 'Все пользователи с ролью moderator';
COMMENT ON VIEW public.admins IS 'Все пользователи с ролью admin';

-- Заявки на регистрацию (для страницы регистрации и модерации)
CREATE TABLE IF NOT EXISTS public.registration_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  full_name text,
  role_requested text NOT NULL DEFAULT 'user' CHECK (role_requested IN ('user', 'moderator', 'admin')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS registration_requests_email_pending_idx
  ON public.registration_requests (email)
  WHERE status = 'pending';

COMMENT ON TABLE public.registration_requests IS 'Заявки с формы регистрации, которые могут одобрять модераторы/админы';
COMMENT ON COLUMN public.registration_requests.role_requested IS 'Желаемая роль: user / moderator / admin';
COMMENT ON COLUMN public.registration_requests.status IS 'Статус заявки: pending / approved / rejected';

------------------------------------------------------------------
-- ЛОГИ ДЕЙСТВИЙ АДМИНОВ/МОДЕРАТОРОВ
------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid,
  actor_email text,
  action text NOT NULL,
  target_type text,
  target_id text,
  details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.activity_logs IS 'Логи действий админов и модераторов';
COMMENT ON COLUMN public.activity_logs.actor_email IS 'Кто совершил действие';
COMMENT ON COLUMN public.activity_logs.action IS 'Короткое имя действия (change_role, approve_request, reject_request и т.п.)';
COMMENT ON COLUMN public.activity_logs.target_type IS 'Тип объекта (user, registration_request и т.п.)';
COMMENT ON COLUMN public.activity_logs.target_id IS 'ID объекта (user_id, request_id и т.п.)';

------------------------------------------------------------------
-- ПРОЕКТЫ, ОТДЕЛЫ И ДОСТУПЫ
------------------------------------------------------------------

-- Отделы / команды
CREATE TABLE IF NOT EXISTS public.departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  parent_id bigint REFERENCES public.departments(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.departments IS 'Отделы и команды компании (иерархическая структура)';

-- Проекты
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  code text,
  description text,
  color text,
  owner_profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.projects IS 'Проекты, которыми управляет система TaskAI';

-- Участники проектов
CREATE TABLE IF NOT EXISTS public.project_members (
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  profile_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member',
  added_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, profile_id)
);

COMMENT ON TABLE public.project_members IS 'Связь пользователей и проектов (участники проектов)';

-- Привязка проектов к отделам
CREATE TABLE IF NOT EXISTS public.project_departments (
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  department_id bigint NOT NULL REFERENCES public.departments(id) ON DELETE CASCADE,
  PRIMARY KEY (project_id, department_id)
);

COMMENT ON TABLE public.project_departments IS 'Какие отделы/команды отвечают за какие проекты';
